"""Defaults for the second multi-asset 5m bot."""

ENTRY_START_SECONDS = 45
ENTRY_CHECK_INTERVAL_SECONDS = 1.5
ENTRY_CHECK_INTERVAL_FAST_SECONDS = 0.5
ENTRY_CHECK_INTERVAL_FAST_THRESHOLD_SECONDS = 12

ENTRY_LIMIT_FLOATING_ENABLED = True
ENTRY_LIMIT_PHASE_RATIO = 0.65
ENTRY_LIMIT_REPRICE_INTERVAL_SECONDS = 0.5
ENTRY_LIMIT_MAX_REPRICES = 2

# (seconds_left, min_edge, capital_pct)
ENTRY_PROFILE_POINTS = [
    (45, 0.040, 0.05),
    (30, 0.032, 0.07),
    (20, 0.027, 0.09),
    (12, 0.022, 0.12),
    (0, 0.020, 0.12),
]

ENABLED_ASSETS = ("btc", "eth", "sol")
ASSET_PRIORITY = ("btc", "eth", "sol")

MIN_BET_USDC = 1.0
BET_SIZING_MODE = "dynamic"
MAX_ODDS = 0.97
FILL_SLIPPAGE_WARN_PCT = 0.02
ENTRY_BALANCE_REFRESH_SECONDS = 10

POLL_INTERVAL_SECONDS = 3
POST_RESOLUTION_BUFFER_SECONDS = 10
WAIT_LOG_INTERVAL_SECONDS = 30

AUTO_REDEEM_ENABLED = True
AUTO_REDEEM_MAX_CONDITIONS_PER_CYCLE = 3
AUTO_REDEEM_ATTEMPT_INTERVAL_SECONDS = 30
AUTO_REDEEM_PROBE_INTERVAL_SECONDS = 30
AUTO_REDEEM_RATE_LIMIT_BUFFER_SECONDS = 5

STOP_LOSS_ENABLED = True
STOP_LOSS_PCT = 0.18
STOP_LOSS_POLL_SECONDS = 1
STOP_LOSS_CONFIRM_TICKS = 2
STOP_LOSS_RETRY_SECONDS = 3

VOLATILITY_FILTER_ENABLED = True
VOLATILITY_REFRESH_SECONDS = 10
VOLATILITY_INTERVAL = "1m"
VOLATILITY_LOOKBACK_CANDLES = 20
VOLATILITY_LOW_THRESHOLD = 0.0018
VOLATILITY_HIGH_THRESHOLD = 0.0040
VOLATILITY_EXTREME_THRESHOLD = 0.0065
VOLATILITY_MIN_ODDS_BUMP_HIGH = 0.006
VOLATILITY_MIN_ODDS_BUMP_EXTREME = 0.012
VOLATILITY_CAPITAL_MULT_LOW = 1.10
VOLATILITY_CAPITAL_MULT_HIGH = 0.75
VOLATILITY_CAPITAL_MULT_EXTREME = 0.45

FAIR_VALUE_SIGMA_FLOOR_PCT = 0.0008
FAIR_VALUE_NO_TRADE_BAND_PCT = 0.00015
FAIR_VALUE_MAX_SPREAD = 0.06
FAIR_VALUE_REQUOTE_THRESHOLD = 0.015
FAIR_VALUE_AGGRESSIVE_EDGE = 0.045
FAIR_VALUE_MIN_MODEL_PROBABILITY = 0.50
FAIR_VALUE_MIN_MARKET_PROBABILITY = 0.45
